#!/bin/sh -xv
# Livro top dia 19 de setembro

myname=make_proglist
outfile="$HOME/proglist"

for dir in `echo "$PATH" | tr ':' ' '`
do
  cd "$dir"

  for file in *
  do
    if [ -x "$file" -a ! -d "$file" ]
    then
      echo "$file"
    fi
  done

done | sort > $outfile
